# Generated by Django 4.1 on 2024-03-28 19:39

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['row', 'seat']},
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre.models.image_file_path),
        ),
        migrations.AddField(
            model_name='play',
            name='image',
            field=models.ImageField(null=True, upload_to=theatre.models.image_file_path),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('performance', 'row', 'seat')},
        ),
    ]
